version: 2.1
orbs:
  gradle: circleci/gradle@3.0.0
  android: circleci/android@2.2.0

jobs:
  gradle-test:
    docker:
      - image: cimg/openjdk:19.0.2
    steps:
      - checkout
      - run: sudo apt update
      - android/change-java-version:
          java-version: 17
      - run: ./gradlew tasks
      - run: ./gradlew check
      - run: ./gradlew test
      - gradle/collect_test_results:
          test_results_path: app/build/test-results
      - store_artifacts:
          path: app/build/test-results
  gradle-build:
    docker:
      - image: cimg/openjdk:19.0.2
    steps:
      - checkout
      - run: sudo apt update
      - android/change-java-version:
          java-version: 17
      - run: ./gradlew build
      - run: ./gradlew run
      - store_artifacts:
          path: app/build

workflows:
  test-gradle:
    jobs:
      - gradle-test
  build-gradle:
    jobs:
      - gradle-build