version: 2.1
orbs:
  gradle: circleci/gradle@3.0.0

jobs:
  gradle-test:
    docker:
      - image: cimg/openjdk:19.0.2
    steps:
      - checkout
      - run: ./gradlew tasks
      - run: ./gradlew check
      - run: ./gradlew test
      - gradle/collect_test_results
        test_results_path: 
      - store_artifacts:
          path: app/build/test-results/TEST-gradle.test.AppTest.xml
  gradle-build:
    docker:
      - image: cimg/openjdk:19.0.2
    steps:
      - checkout
      - ./gradlew build
      - ./gradlew run

workflows:
  test-gradle:
    jobs:
      - gradle-test
  build-gradle:
    jobs:
      - gradle-build